apiVersion: v1
kind: Secret
metadata:
  name: flux-system
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  githubAppID: "{{ .Values.githubApp.id }}"
  githubAppInstallationID: "{{ .Values.githubApp.installationId }}"
  githubAppPrivateKey: |-
    {{ .Values.githubApp.privateKey | nindent 4 }}
