name: Release Helm Charts

on:
  push:
    tags:
      - '*/v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Extract Chart and Version
        id: extract
        run: |
          tag=${GITHUB_REF#refs/tags/}
          chart_name="${tag%%/v*}"
          version="${tag#*/v}"
          echo "chart_name=$chart_name" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Package and Push Chart
        run: |
          helm package ${{ steps.extract.outputs.chart_name }} --version ${{ steps.extract.outputs.version }} --app-version ${{ steps.extract.outputs.version }}
          helm push ${{ steps.extract.outputs.chart_name }}-${{ steps.extract.outputs.version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
